# Generated by Django 4.2.3 on 2023-08-09 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0002_sinhvien_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinhvien',
            name='user',
        ),
    ]
