# Generated by Django 4.2.3 on 2023-08-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0003_remove_sinhvien_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinhvien',
            name='xep_hang',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
